### ISSUE TITLE
Panopticlick recommends installing Privacy Badger to Tor users

### ISSUE THREAD

**Issue by ghostwords** [EFForg/cover-your-tracks#50]
We should not be recommending Privacy Badger to Tor users:

> It is strongly discouraged to install additional add-ons, and the Tor Project will not offer support for these configurations.

-- https://tb-manual.torproject.org/plugins/#browser-add-ons

**Comment by ghostwords** [comment]
Previously: #32.

**Comment by Hainish** [comment]
We're going to simplify the results page in an upcoming iteration.  This should show all positive results for Tor Browser, since Tor Browser users are not really trackable due to the implementation of robust fingerprinting protection and first-party isolation.  Changing the results page to all-positive results will also remove any recommendations.

**Comment by pipboy96** [comment]
@Hainish Here's the code to test for Tor Browser:

```js
function isTorBrowser() {
  return (
    /firefox/i.test(navigator.userAgent) &&

    // Test for presence of anti-fingerprinting features built into Tor Browser

    // Tor Browser rounds the window size down to the nearest number divisible by 100,
    // and also makes the outer size equal to the outer size

    innerWidth === outerWidth &&
    innerHeight === outerHeight &&
    innerWidth % 100 === 0 &&
    outerHeight % 100 === 0 &&

    // Test for time zone hiding (Tor Browser always reports the time zone as UTC+0)
    new Date().getTimezoneOffset() === 0
  );
}
```

**Comment by Thorin-Oakenpants** [comment]
@pipboy96 : That can produce false positives. I have a 100% reliable method if anyone is interested, not only if it is Tor Browser (vs any other gecko build), but also if `privacy.resistFingerprinting` is enabled

**Comment by Thorin-Oakenpants** [comment]
The above test is not 100% effective: timezone offset can be spoofed, userAgent can be spoofed, and inner widths can be incorrect: when letterboxing is disabled, due to bugs or if the user changes the dimensions via full-screen, maximizing, manual resizing or zooming - using measurements is not stable

@Hainish , if you are interested, I have a 100% reliable way, with no false positives, to return that the browser is Tor Browser (~15ms), and that RFP is enabled (< 1ms). Works on all TB's going back to at least ESR60, and fully cross-platform. That would be the first step in only evaluating Tor Browser for a possible free pass.

The second step, **_which only matters if you care about the integrity of RFP_**, would be to check several metrics [1] [2] have not been compromised: if they are, then the fingerprint has been compromised and you should not give it a free pass. It depends on how far down you want to dig to find something amiss that the user has tinkered with. However, almost all of this could all be skipped, by just checking for extension lies via prototype (~70ms)

I offered to help once before and was met with dead silence. While I'm not a fan of giving "free passes" (which is why I think step 2 is important), I am also painfully aware that Tor Browser users do not always interpret the results correctly, and giving Brave a higher rating is highly misleading [3]. A reply would be appreciated - TIA

[1] some basic fast checks
- inner window = screen = available screen = outer
- inner and outer x.y positions are all `0`
- timezone offset via dateParse() is `0`
- hardwareConcurrency = `2`
- devicePixelRatio is `1`
- navigator properties: user agent (but to do it properly requires knowing the OS and browser version, which can also be 100% reliably detected)

[2] maybe: not as fast: but you already check randomizing per eTLD+1. If you know it's Tor Browser you can skip that and test per-execution which doesn't really add any extra perf
- canvas should be random per execution (since ESR78): users can give sites exceptions, or worse revert to the pre ESR78 behavior. While this does not compromise the full fingerprint, it should be noted IMO

[3] Just because Brave randomizes more than one metric, does not make it any more effective. It is true that some scripts have been found that do not use canvas, and additional randomized metrics might help, but this is very rare. Outside those rare scripts (which is also not an issue for Tor Browser), RFP is just as effective as fooling them, if they are naive. You are **_already demonstrating_**, the randomness is negated in **_your own test_** and values returned are static, i.e you are recording "randomized" and not the spoofed value. I do get that you're trying to apply your results to real world scenarios, but I think you need to rethink how you rate randomized values

**Comment by Thorin-Oakenpants** [comment]
and... dead silence... I guess no-one is paying attention (it's only been a week) or no-one wants a solution... or I come across as some sort of snake-oil salesman? For the record, I have been involved somewhat (not employed by either Mozilla or Tor Project) with RFP and Tor Uplift almost since it's inception. Not going to ask again, I have better things to do
