### ISSUE TITLE
Tests stating no protection with Privacy Badger and Firefox

### ISSUE THREAD

**Issue by Protonator** [EFForg/cover-your-tracks#52]
Since version 2020.10.7 of Privacy Badger, the Panopticlick tests in Firefox 82.X are stating that there are no active protections against anything and recommending to install Privacy Badger.

![Panopticlick FF](https://user-images.githubusercontent.com/53665966/97791105-133ee000-1bcf-11eb-9c60-cdf6fb801531.jpg)

I also tested this with a complete fresh Firefox profile and got the same result. The tracking protection of Firefox itself was inactive for the tests. Privacy Badger does work on other websites, though. And the Chromium-Edge with Privacy Badger and same settings doesn't show this behaviour.

**Comment by ghostwords** [comment]
Hello!

Speaking from Privacy Badger's perspective, test three is failing because of https://github.com/EFForg/badger-sett/issues/59#issuecomment-719974612 and https://github.com/EFForg/privacybadger/issues/2708#issuecomment-719963668.

Tests one and two are probably also failing because of https://github.com/EFForg/badger-sett/issues/59#issuecomment-719974612

Test four failing is a long-outstanding issue: #53

**Comment by ghostwords** [comment]
To summarize, recent-ish changes made as part of https://www.eff.org/badger-evolution broke the first three tests.

The fingerprinting test has been broken for the longest time because (my current understanding is that) what Panopticlick tests for and what [Privacy Badger actually does about fingerprinting](https://privacybadger.org/#Does-Privacy-Badger-prevent-fingerprinting) are misaligned.

**Comment by Protonator** [comment]
Thanks for the informations. By the way: The tests are failing in Chromium-Edge now, too. I don't know why they succedded before – perhaps I had enabled the Edge tracking protection back then.

**Comment by ghostwords** [comment]
>But why are the tests in Chromium-Edge without its tracking protection and with the same Privacy Badger version (with disabled automatic learning) not failing?

I think this is another bug, #54

I don't know why the "acceptable ads" test passes though.

**Comment by ghostwords** [comment]
This will be fixed in the next Privacy Badger update.

**Comment by ghostwords** [comment]
This should be fixed.
